### PR TITLE
Testing if codecov crashes on external pull requests for master

### PR DESCRIPTION
**Pull request by leonardoInf**
hopefully not

### CODE REVIEW

**Comment by leonardoInf** [comment]
There are some other isssues here maybe this? https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

**Comment by leonardoInf** [comment]
I would like to see you come back to fix your CI tools or disable them so that contributors can commit

**Comment by Sharparam** [comment]
@leonardoInf Sorry, been away the past couple of weeks. I've pushed a commit to the release branch that should hopefully resolve the AppVeyor issue. If you can rebase again and see if it builds that would be great!

**Comment by Sharparam** [comment]
Probably in #267 though as this PR seems to be against the `master` branch which does not have up-to-date build configuration (it has the old TeamCity build setup).

**Pull request closed without merging**
